// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HistoryDocumentDataSlicesSlice = HistorySlice;

/**
 * Content for history documents
 */
interface HistoryDocumentData {
  /**
   * Slice Zone field in *history*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: history.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HistoryDocumentDataSlicesSlice> /**
   * Meta Title field in *history*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: history.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *history*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: history.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *history*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: history.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * history document from Prismic
 *
 * - **API ID**: `history`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HistoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HistoryDocumentData>,
    "history",
    Lang
  >;

type SkillsDocumentDataSlicesSlice = SkillsSlice;

/**
 * Content for skills documents
 */
interface SkillsDocumentData {
  /**
   * Slice Zone field in *skills*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SkillsDocumentDataSlicesSlice> /**
   * Meta Title field in *skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: skills.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: skills.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *skills*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SkillsDocumentData>,
    "skills",
    Lang
  >;

export type AllDocumentTypes = HistoryDocument | SkillsDocument;

/**
 * Item in *History → Default → Primary → History*
 */
export interface HistorySliceDefaultPrimaryHistoryItem {
  /**
   * icon field in *History → Default → Primary → History*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.history[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * role field in *History → Default → Primary → History*
   *
   * - **Field Type**: Text
   * - **Placeholder**: your role in company
   * - **API ID Path**: history.default.primary.history[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * company field in *History → Default → Primary → History*
   *
   * - **Field Type**: Text
   * - **Placeholder**: name of company
   * - **API ID Path**: history.default.primary.history[].company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * start_job field in *History → Default → Primary → History*
   *
   * - **Field Type**: Date
   * - **Placeholder**: date of starting job
   * - **API ID Path**: history.default.primary.history[].start_job
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_job: prismic.DateField;

  /**
   * leave_job field in *History → Default → Primary → History*
   *
   * - **Field Type**: Date
   * - **Placeholder**: date of leaving job
   * - **API ID Path**: history.default.primary.history[].leave_job
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  leave_job: prismic.DateField;
}

/**
 * Primary content in *History → Default → Primary*
 */
export interface HistorySliceDefaultPrimary {
  /**
   * History field in *History → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: history.default.primary.history[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  history: prismic.GroupField<Simplify<HistorySliceDefaultPrimaryHistoryItem>>;
}

/**
 * Default variation for History Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *History*
 */
type HistorySliceVariation = HistorySliceDefault;

/**
 * History Shared Slice
 *
 * - **API ID**: `history`
 * - **Description**: History
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistorySlice = prismic.SharedSlice<
  "history",
  HistorySliceVariation
>;

/**
 * Item in *Skills → Default → Primary → skills*
 */
export interface SkillsSliceDefaultPrimarySkillsItem {
  /**
   * icon field in *Skills → Default → Primary → skills*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skills[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * name field in *Skills → Default → Primary → skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: name of the skill
   * - **API ID Path**: skills.default.primary.skills[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * link field in *Skills → Default → Primary → skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: link to website of this skill
   * - **API ID Path**: skills.default.primary.skills[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Primary content in *Skills → Default → Primary*
 */
export interface SkillsSliceDefaultPrimary {
  /**
   * skills field in *Skills → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<SkillsSliceDefaultPrimarySkillsItem>>;
}

/**
 * Default variation for Skills Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SkillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Skills*
 */
type SkillsSliceVariation = SkillsSliceDefault;

/**
 * Skills Shared Slice
 *
 * - **API ID**: `skills`
 * - **Description**: Skills
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillsSlice = prismic.SharedSlice<"skills", SkillsSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HistoryDocument,
      HistoryDocumentData,
      HistoryDocumentDataSlicesSlice,
      SkillsDocument,
      SkillsDocumentData,
      SkillsDocumentDataSlicesSlice,
      AllDocumentTypes,
      HistorySlice,
      HistorySliceDefaultPrimaryHistoryItem,
      HistorySliceDefaultPrimary,
      HistorySliceVariation,
      HistorySliceDefault,
      SkillsSlice,
      SkillsSliceDefaultPrimarySkillsItem,
      SkillsSliceDefaultPrimary,
      SkillsSliceVariation,
      SkillsSliceDefault,
    };
  }
}
